if not (vim.pack and vim.pack.add) then
	vim.notify("vim.pack is unavailable. Upgrade to a Neovim build with vim.pack support.", vim.log.levels.ERROR)
	return
end

require("plugins.autopairs")
require("plugins.autosave")
require("plugins.colors")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.highlight-colors")
require("plugins.alpha")
require("plugins.lualine")
require("plugins.oil")
require("plugins.surround")
require("plugins.neogit")
require("plugins.go-up")
require("plugins.dap")
require("plugins.teamtype")
require("plugins.dropbar")
require("plugins.image")
require("plugins.markdown")
require("plugins.fidget")
require("plugins.jump")
require("plugins.pi")
